gaul/s3proxy

- pom.xml
Changelog:
http://dev.eclipse.org/mhonarc/lists/jetty-announce/msg00072.html
> Upgrade to Jetty 9.2.7.v20150116

- src/main/java/org/gaul/s3proxy/S3Proxy.java
- src/main/resources/checkstyle.xml
- src/test/java/org/gaul/s3proxy/S3ProxyTest.java
Also hoist sanity checks out of main.
> Use builder to create S3Proxy

- pom.xml
- src/test/java/org/gaul/s3proxy/S3AwsSdkTest.java
Adds a unit test with the Amazon Java SDK for failures when submitting
v4-signed requests.
> Add a test for failure when using v4 signatures.

- src/main/java/org/gaul/s3proxy/S3ProxyHandler.java
https://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html#VirtualHostingSpecifyBucket
> correctly follow the host header documentation

- src/main/java/org/gaul/s3proxy/S3ProxyHandler.java
> Include Content-Range header in range requests

- src/main/java/org/gaul/s3proxy/S3ProxyHandler.java
- src/test/java/org/gaul/s3proxy/S3ProxyTest.java
> Allow anonymous access via bucket and object ACLs

- src/main/java/org/gaul/s3proxy/S3ProxyHandler.java
Also handle checking existence.
> Handle listing a public-read container

- src/main/java/org/gaul/s3proxy/S3ProxyHandler.java
- src/test/java/org/gaul/s3proxy/S3ProxyTest.java
> Add support for conditional get

- src/main/java/org/gaul/s3proxy/ChunkedInputStream.java
- src/main/java/org/gaul/s3proxy/S3AuthorizationHeader.java
- src/main/java/org/gaul/s3proxy/S3ErrorCode.java
- src/main/java/org/gaul/s3proxy/S3ProxyHandler.java
- src/test/java/org/gaul/s3proxy/S3AwsSdkTest.java
> Support AWS v4 signatures

- src/main/java/org/gaul/s3proxy/S3ProxyHandler.java
- src/test/java/org/gaul/s3proxy/S3AwsSdkTest.java
This makes MPU overwrites of an existing blob atomic.  Fixes #108.
> Use uploadId for stub blob name

- .travis.yml
- Dockerfile
> Provide Dockerfile

- src/main/java/org/gaul/s3proxy/Main.java
- src/main/java/org/gaul/s3proxy/S3Proxy.java
- src/main/java/org/gaul/s3proxy/S3ProxyConstants.java
- src/main/java/org/gaul/s3proxy/S3ProxyHandler.java
> Add property to include permissive CORS response

- Dockerfile
- src/main/resources/run-docker-container.sh
refs issues #142
refs Pull #144
The default value is false
> Added Docker environment variable "S3PROXY_CORS_ALLOW_ALL"

- src/test/java/org/gaul/s3proxy/AwsSdkTest.java
Verify Content-Disposition and Content-Type header in response of pre-signed URL.
> Add verification of override parameters for presigned url.

- src/main/java/org/gaul/s3proxy/S3ProxyHandler.java
I tried to not to refactor the code. The only thing I refactored it the way how the fields are checked by adding the `isField` method and some convenient method to calculate HmacSHA1 / HmacSHA256 because they share code.
I also added CORS headers.
closes #212
Let me know what you think.
> HTTP POST Requests using AWS Signature Version 4

- src/main/java/org/gaul/s3proxy/S3ProxyHandler.java
- src/main/java/org/gaul/s3proxy/S3ProxyHandlerJetty.java
This avoids silent failures on blob PUTs, as seen when proxying B2.
When the server closes the connection (timeouts on slow uploads, or keep-alive connections too old), causing an `IOException` (sorry, don't have the stack trace anymore) before the upload has finished, the error was not caught, making the client think that the upload went through.
502 seems to be an appropriate code for clients to go ahead and retry as expected - fixed the backup application I'm using.
> Return error when no error response

- pom.xml
Upgrade to jackson-dataformat-xml 2.8.8
Changelog:
https://github.com/FasterXML/jackson-dataformat-xml/blob/master/release-notes/VERSION
https://github.com/FasterXML/jackson-core/blob/master/release-notes/VERSION
> Upgrade to jackson-dataformat-xml 2.8.8

- src/main/java/org/gaul/s3proxy/AwsSignature.java
- src/main/java/org/gaul/s3proxy/S3ProxyHandler.java
Signed-off-by: Chaithanya Ganta <ganta@adobe.com>
As part of fixing #169, moving signature creation logic to AwsSignature class.
> Moving signature creation logic to a seperate class

- src/main/java/org/gaul/s3proxy/S3ProxyHandler.java
> Emit InvalidArgument on CopyPart invalid range

- CHANGELOG.md
- pom.xml
- src/main/assembly/jar-with-dependencies.xml
- src/main/config/logback.xml
> Shade and relocate Jetty dependencies

- .gitignore
- pom.xml
- src/main/java/org/gaul/s3proxy/junit/S3ProxyRule.java
- src/main/java/org/gaul/s3proxy/junit/rules/S3ProxyRule.java
- src/test/java/org/gaul/s3proxy/junit/S3ProxyRuleTest.java
- src/test/java/org/gaul/s3proxy/junit/rules/S3ProxyRuleTest.java
> Add JUnit Rule to project

- Dockerfile
> Use Java 11 slim image

- pom.xml
I spotted this via a Snyk coding session and thought I might as well contribute it, feel free to ignore if not useful at this moment.
> Upgrade Jackson to 2.13.3

- src/main/java/org/gaul/s3proxy/S3Proxy.java
Address https://github.com/gaul/s3proxy/issues/579
> Increase max non chunked request size to 128 MB

- Dockerfile
> Upgrade Docker JRE to 17

- src/main/java/org/gaul/s3proxy/S3ProxyHandler.java
> Change timestamp validation for presigned urls

- src/main/java/org/gaul/s3proxy/S3Proxy.java
Simplify S3Proxy usage in Java when an SSLContext instance is already at hand and creating keystore files is inconvenient.
> Support SSL setup via SSLContext in S3Proxy.Builder

- src/main/java/org/gaul/s3proxy/S3ProxyHandler.java
Fix Duplicate key error when using handleCompleteMultipartUpload with azure blob
> fix handleCompleteMultipartUpload bug

- .github/workflows/ci-main.yml
> Run s3-tests against Azurite in CI

- .github/workflows/ci-main.yml
Also clean up some incorrect tagging.
> Run s3-tests against minio

- src/main/java/org/gaul/s3proxy/nio2blob/AbstractNio2BlobStore.java
- src/test/java/org/gaul/s3proxy/AwsSdkTest.java
Reported-by: Nico Waisman <nico@xbow.com>
> Prevent parent path traversal in filesystem-nio2
