gaul/s3proxy

src/main/java/org/gaul/s3proxy/S3Proxy.java
src/test/java/org/gaul/s3proxy/S3ProxyTest.java

The commit adds a getState() method, which exposes the Jetty state
to the caller. This is useful to check whether the server is running
or is in some other state.

Expose the Jetty state in the S3Proxy interface.

---

pom.xml
src/main/assembly/jar-with-dependencies.xml

This works around MSHADE-183 which prevents use with Maven 3.2.5 and
has caused recent Travis CI failures.

Use maven-assembly-plugin instead of Maven Shade

---

src/main/java/org/gaul/s3proxy/S3ErrorCode.java
src/main/java/org/gaul/s3proxy/S3ProxyHandler.java
src/test/java/org/gaul/s3proxy/S3ProxyTest.java

This approach requires three times as many operations as the optimal
approach.  Implementing this correctly requires exposing the
underlying multipart operations in jclouds.  Most s3-tests pass but
two still fail:
test_multipart_upload_size_too_small
test_list_multipart_upload
References #2.

Emulate multipart upload with single-part uploads

---

src/main/java/org/gaul/s3proxy/S3ProxyHandler.java

this is to accomodate using s3proxy with swift backend, which has
a colon in the access key

parse authorization header backwards

---

src/main/java/org/gaul/s3proxy/S3ProxyHandler.java
src/test/java/org/gaul/s3proxy/S3ProxyTest.java

Enables support for the delimiter option.
Amends a recursive test to expect that the delimiter is included in
the common prefix name.

Enable delimiter support.

---

src/main/java/org/gaul/s3proxy/Main.java

Terminate on s3proxy start failure

---

src/main/java/org/gaul/s3proxy/EventualBlobStore.java
src/main/java/org/gaul/s3proxy/Main.java
src/main/java/org/gaul/s3proxy/S3ProxyConstants.java
src/test/java/org/gaul/s3proxy/EventualBlobStoreTest.java

This models eventually-consistent behavior.  This implementation uses
two buckets and with client writes going to the first bucket and reads
to the second.  Operations are replicated from the first to the second
with a variable delays.  A more complete implementation could flap
between the strongly- and eventually-consistent buckets and arbitrary
reorder operations which conclude with last-writer wins.  Fixes #65.

Add EventualBlobStore

---

src/main/java/org/gaul/s3proxy/S3ProxyHandler.java
src/test/java/org/gaul/s3proxy/AwsSdkTest.java

has override parameters, i.e. "content-disposition",
"response-content-encoding".

This change makes S3Proxy able to validate presigned url which 

---

src/main/java/org/gaul/s3proxy/Main.java
src/main/java/org/gaul/s3proxy/S3Proxy.java
src/main/java/org/gaul/s3proxy/S3ProxyConstants.java
src/main/java/org/gaul/s3proxy/S3ProxyHandler.java
src/main/java/org/gaul/s3proxy/S3ProxyHandlerJetty.java

Presigned URLs may contain additional parameters in the URL which will
be used “as is” by the client uploading/downloading content from S3.
CLOSES #138

Add support for ignoring unknown parameters

---

src/main/config/logback.xml
src/test/resources/logback.xml

In distributed service environment this helps to distinguish s3proxy logs with other service logs.

Added log prefix in logback

---

src/main/java/org/gaul/s3proxy/Main.java
src/main/java/org/gaul/s3proxy/S3Proxy.java
src/main/java/org/gaul/s3proxy/S3ProxyConstants.java
src/main/java/org/gaul/s3proxy/S3ProxyHandler.java
src/main/java/org/gaul/s3proxy/S3ProxyHandlerJetty.java
src/test/java/org/gaul/s3proxy/AwsSdkTest.java
src/test/java/org/gaul/s3proxy/JcloudsBucketsLiveTest.java
src/test/java/org/gaul/s3proxy/JcloudsS3BlobIntegrationLiveTest.java
src/test/java/org/gaul/s3proxy/JcloudsS3BlobSignerLiveTest.java
src/test/java/org/gaul/s3proxy/JcloudsS3ClientLiveTest.java
src/test/java/org/gaul/s3proxy/JcloudsS3ContainerIntegrationLiveTest.java
src/test/java/org/gaul/s3proxy/TestUtils.java
src/test/resources/s3proxy.conf

Sometimes service is not the only service under a domain(hostname). This work adds s3proxy.service-path to allow s3proxy to be deployed with a service path. The issues resolved by adding service path are 1) properly extract bucket and key, 2) properly validate signagure for authentication, 3) properly validate signagure for presigned url. Test cases are changed to run when s3proxy.service-path is set.

Support service path

---

src/main/java/org/gaul/s3proxy/S3ProxyHandler.java

For blob stores for which there is no blob access control, testHttpClient test is failing. For these blob stores by default getBlobAccess returns private. If a bucket is public then we should allow public access of the blob. This pull request fixes this issue

Fixed failing test in case of azure

---

src/main/java/org/gaul/s3proxy/S3ProxyHandler.java

This allows clients to list pseudo-directories with slashes in them.
References kahing/goofys#213.

Do not escape / when URL encoding

---

src/main/java/org/gaul/s3proxy/S3ProxyHandler.java

Added simple check for non anonymous identity before attempting to read the auth header values.
List bucket and create bucket operations performed vial curl and aws cli now work as expected.
Fixes #251

gaul/s3proxy#251 Add check for non anonymous identity before extracting auth header

---

Dockerfile

This allows developers and users to build their own version of s3proxy fully in Docker without the need of external builders for the s3proxy binary.
This pull depends on features that have been recently released in the [17.05](https://github.com/moby/moby/blob/17.05.x/CHANGELOG.md#builder) version of Docker which may not be preferable for some older build environments.

Update Dockerfile to use multistage building.

---

src/main/java/org/gaul/s3proxy/S3ProxyHandler.java

re #237 This makes all responses specify a character encoding of `UTF-8`. The cause of the inconsistent behaviour was jetty's configuration which uses `charset=ISO-8859-1` as its default if none other is given and jetty does not include a default character encoding for `application/xml`.
As jetty will add the encoding if it is not present, forcing `UTF-8` seems the most sensible solution and all the AWS xml responses specify an XML encoding of `UTF-8` in the xml preamble `<?xml version="1.0" encoding="UTF-8"?>`.

Add `UTF-8` character encoding to all S3 responses

---

Dockerfile

Java is deprecated as the state:
"This image is officially deprecated in favor of the openjdk image, and will receive no further updates after 2016-12-31 (Dec 31, 2016). Please adjust your usage accordingly."
I adjusted it to the corresponding 7-alpine-jre tag  from openjdk
https://hub.docker.com/_/openjdk/
the MAINTAINER instruction is deprecated as of Docker Version: 
1.13.0
https://docs.docker.com/engine/deprecated/#maintainer-in-dockerfile
all the best

update depcrecated image, fix minor Label change

---

Dockerfile
src/main/resources/run-docker-container.sh

Also, default to`jcloud.regions=us-east-1` to avoid issues with the nodejs aws sdk like the one described in #202.

Allow setting property jclouds.regions via env variables when running in docker

---

Dockerfile
src/main/resources/run-docker-container.sh

As already documented in the Wiki https://github.com/gaul/s3proxy/wiki/Storage-backend-examples#swift-keystone-v30, you can use a Swift backend with Keystone v3 authentification.
This PR makes the needed `jcloud` configuration options available in the Dockerfile and pass the environment as properties to the java runtime.

Keystone v3 support with properties

---

README.md
src/main/java/org/gaul/s3proxy/S3ProxyHandler.java
src/test/java/org/gaul/s3proxy/AwsSdkTest.java

Not supporting `fetch-owner` until jclouds adds support for this.
Several applications like AWS CLI now require this RPC.

Add partial support for list objects v2

---

src/main/java/org/gaul/s3proxy/Main.java

I've tried to use the proxy for OVH swift storage and got the same problem as #81 . The main problem was that `BlobStore blobStore = context.getBlobStore();` tries to compare different endpoints basing on values of the dictionary returned by the OVH API and the JCLOUDS_ENDPOINT variable. It mismatches hardly and it's falling back to the first region, that is DE1.
`[s3proxy] W 03-05 23:32:53.312 main o.j.l.s.i.GetRegionIdMatchingProviderURIOrNull:74 |::] failed to find key for value https://auth.cloud.ovh.net/v3/ in {DE1=https://storage.de1.cloud.ovh.net/v1/AUTH_d443, UK1=https://storage.uk1.cloud.ovh.net/v1/AUTH_d443, WAW1=https://storage.waw1.cloud.ovh.net/v1/AUTH_d443, GRA5=https://storage.gra5.cloud.ovh.net/v1/AUTH_d443, BHS3=https://storage.bhs3.cloud.ovh.net/v1/AUTH_d443, …

Fix for OVH swift storage (url mismatch for region)

---

src/main/java/org/gaul/s3proxy/S3Exception.java
src/main/java/org/gaul/s3proxy/S3ProxyHandler.java

S3Proxy should check the format of the x-amz-copy-source-range value
when handling an UploadPartCopy request. The patch changes the behavior
to return an InvalidArgument error along with the matching error
description to AWS S3. To match the error format, the S3Exception class
is modified to return the actual error message, rather than the String
version of the error code.
Corresponding tests will be added to ceph/s3-tests.
Fixes: #304

UploadPartCopy: Fail if improper source range.

---

src/main/java/org/gaul/s3proxy/S3ProxyHandler.java
src/test/java/org/gaul/s3proxy/junit/S3ProxyRuleTest.java

Fixes #299 
Issue:
1. `AmazonS3Client#doesBucketExistV2(String bucketName)`
2. internally uses `AmazonS3Client#getBucketAcl(String bucketName)`
3. The `S3ProxyHandler` thew an exception on a GET Bucket ACL request for buckets that do not exist. 
Fixed it by making sure the `S3ProxyHandler` GET Bucket ACL correctly responds with a 404 if the bucket does not exist.

Fixes #299

---

src/main/java/org/gaul/s3proxy/S3ProxyHandler.java

Currently canonical_request is based on a canonical_uri for which bucket name is prepend
if dns path style is used which is not compatible with s3v4 signature mechanism
Closes #321

Use original uri to compute canonical_request in s3v4 signature

---

src/main/java/org/gaul/s3proxy/S3ProxyHandler.java
src/test/java/org/gaul/s3proxy/CrossOriginResourceSharingRuleTest.java

Adding CORS headers Access-Control-Allow-Origin and Access-Control-Allow-Methods in Multipart Responses if the
Origin Header is included in the Request and does match the CORS rules.
This was requested in #331.
Unfortunately my spare time is very limited at the moment and I was not able to write a test case for the multi part uploads. I tried, but there seems to be no easy way to retrieve the response Headers e.g. from InitiateMultipartUploadResult like here: https://github.com/gaul/s3proxy/blob/master/src/test/java/org/gaul/s3proxy/AwsSdkTest.java#L481-L482 to verify that CORS headers are present.
So maybe some else could step in here and add a test.
I am sorry that I cannot provide more in the moment.
Super-seeds #332

CORS header for MultiPart Requests

---

Dockerfile
src/main/resources/run-docker-container.sh

This project used the env var `S3PROXY_VIRTUALHOST`, but then this PR: #341 added another declaration that used `S3PROXY_VIRTUAL_HOST`.
This PR fixes this, and goes back to `S3PROXY_VIRTUALHOST`.
Thanks !

Use the old environment variable for virtual host

---

src/main/java/org/gaul/s3proxy/CrossOriginResourceSharing.java
src/main/java/org/gaul/s3proxy/S3Proxy.java
src/main/java/org/gaul/s3proxy/S3ProxyHandler.java
src/test/java/org/gaul/s3proxy/CrossOriginResourceSharingAllowAllResponseTest.java
src/test/java/org/gaul/s3proxy/CrossOriginResourceSharingResponseTest.java
src/test/resources/s3proxy-cors-allow-all.conf

If the allowed origin `*` is configured e.g. through config option `s3proxy.cors-allow-all=true` the `ACCESS_CONTROL_ALLOW_ORIGIN` header in CORS responses will now always be `*` and not the requested host from the `Origin` header. If only concrete allowed origins are configured the behaviour remains unchanged.
Furthermore the `ACCESS_CONTROL_ALLOW_METHODS` header will always include all allowed methods in the CORS response.
This is inline with a native S3 CORS response and will help esp. in CDN caching scenarios. All requested Origins can be served with a cached response.
Further changes:
* S3Proxy only accepts allowed methods from `CrossOriginResourceSharing.SUPPORTED_METHODS`, preventing operators to configure methods which do not provide CORS headers atm, like `HEAD` or `DELETE`.
* If …

Better support for caching scenarios of CORS responses

---

src/main/java/org/gaul/s3proxy/CrossOriginResourceSharing.java
src/main/java/org/gaul/s3proxy/S3ProxyHandler.java

This makes it possible to construct the S3ProxyHandler.  
Making the CrossOriginResourceSharing public with public constructors caused more CheckStyle errors because of all the finals.
In my testing with AWS client v2 I also had to add HEAD to the methods.

Make CORS handling optional

---

src/main/java/org/gaul/s3proxy/S3ProxyHandler.java

This recursively combines up to 32 sets of 32 parts, allowing 1024
part multipart uploads.  Fixes #330.

Allow GCS backend to upload more than 32 parts

---

pom.xml

Release notes:
https://github.com/FasterXML/jackson-dataformat-xml/blob/2.12/release-notes/VERSION-2.x

Upgrade to jackson-dataformat-xml 2.12.3

---

README.md
src/main/java/org/gaul/s3proxy/Main.java
src/main/java/org/gaul/s3proxy/S3ProxyConstants.java
src/main/java/org/gaul/s3proxy/ShardedBlobStore.java
src/test/java/org/gaul/s3proxy/ShardedBlobStoreTest.java
src/test/java/org/gaul/s3proxy/TestUtils.java

Adds the sharded bucket middleware, which allows for splitting objects
across multiple backend buckets for a given virtual bucket. The
middleware should be configured as:
```
s3proxy.sharded-blobstore.<bucket name>.shards=<number of shards>
s3proxy.sharded-blobstore.<bucket name>.prefix=<prefix>
```
All shards are named <prefix>-<index>, where index is an
integer from 0 to <number of shards> - 1. If the <prefix> is not
supplied, the <bucket name> is used as the prefix.
Listing the virtual bucket and multipart uploads are not supported. When
listing all containers, the shards are elided from the result.

Add Sharded Bucket middleware

---

src/main/java/org/gaul/s3proxy/S3ProxyHandler.java

Background: I was trying to use the [S3 backup feature of FoundationDB](https://apple.github.io/foundationdb/backups.html) with s3proxy to do backups on Azure. This did not work, because the date header sent by the backup tool is in Iso8601 format.
This PR adds code to parse the date header in Iso8601 if the default header parsing fails.

Support Iso8601 in date headers

---

src/main/java/org/gaul/s3proxy/AliasBlobStore.java
src/main/java/org/gaul/s3proxy/Main.java
src/main/java/org/gaul/s3proxy/S3ProxyConstants.java
src/test/java/org/gaul/s3proxy/AliasBlobStoreTest.java

Alias middleware implements a way to remap backend buckets to a
configurable front-end name. The mappings are configured as:
s3proxy.alias-blobstore.<s3proxy bucket> = <backend bucket>
A single bucket cannot be mapped to multiple names.

Alias middleware to remap backend buckets

---

.github/workflows/run-tests.yml

https://github.com/actions/setup-java/blob/main/README.md
```
NOTE: Adopt OpenJDK got moved to Eclipse Temurin and won't be updated anymore. 
It is highly recommended to migrate workflows from adopt to temurin 
to keep receiving software and security updates.
```

ci: Temurin JDK

---

src/main/java/org/gaul/s3proxy/S3ProxyHandler.java

Makes S3Proxy compatible with ExAws by testing for query string parameter _presence_ on endpoints, instead of equality to empty string.

ExAws compatibility

---

src/main/resources/run-docker-container.sh

When using s3proxy as a proxy for S3 -> Azure Blob Storage, one needs to set the authentication parameters. When running in a container, these can be exposed via environment variables, but are currently not passed through to the jclouds config.
This is how we got it running for us in a custom build of the container.
Should I also add the options for other backends? Or do you see options for a generic solution?
Maybe also corresponds to #404

Docker entrypoint: authentication for Azure Blob

---

README.md
pom.xml
src/main/java/org/gaul/s3proxy/AwsSignature.java
src/main/java/org/gaul/s3proxy/S3ErrorCode.java
src/main/java/org/gaul/s3proxy/S3Proxy.java
src/main/java/org/gaul/s3proxy/S3ProxyHandler.java
src/main/java/org/gaul/s3proxy/S3ProxyHandlerJetty.java
src/test/java/org/gaul/s3proxy/AwsSdkTest.java

Jetty 9 is EOL.  This requires Java 11 and updating some Java EE
imports.  Fixes #422.

Upgrade to Jetty 11.0.11

---

src/main/resources/run-docker-container.sh

Add a `S3PROXY_JAVA_OPTS` environment variable into the run-docker-container.sh file. This will allow users to easily pass in custom options to the JVM. 
For example, my use case is to pass `-Xmx` and `-Xms` which can be passed using this variable

Add S3PROXY_JAVA_OPTS environment variable

---

Dockerfile
README.md
src/main/resources/run-docker-container.sh

Following #512, we need to add support for the "secure endpoint" parameter through environment variables. I also added a default value for the chunked request size (found in the java code source) since an empty value will raise an exception:
```
[s3proxy] E 04-20 10:16:36.854 main org.gaul.s3proxy.Main:279 |::] java.lang.NumberFormatException: For input string: ""
[s3proxy] E 04-20 10:16:36.855 main org.gaul.s3proxy.Main:279 |::]     at java.base/java.lang.NumberFormatException.forInputSt
[s3proxy] E 04-20 10:16:36.855 main org.gaul.s3proxy.Main:279 |::]     at java.base/java.lang.Long.parseLong(Unknown Source)
[s3proxy] E 04-20 10:16:36.855 main org.gaul.s3proxy.Main:279 |::]     at java.base/java.lang.Long.parseLong(Unknown Source)
[s3proxy] E 04-20 10:16:36.856 main …
```

Add missing environment variable for secure endpoint

---

src/main/java/org/gaul/s3proxy/S3ProxyHandler.java

Currently pagination is broken for backends that use opaque markers. It is so because the key (`last key from the set`) under which a real marker is saved is different than the key (`encoded marker`) that S3Proxy is trying to use to read a real marker.
It results with S3Proxy being able to fetch only 1 page:
```
2023-07-04 14:02:31         13 hw
2023-07-04 14:37:11         13 hw-a-0
2023-07-04 14:43:21         13 hw-aa-0
2023-07-04 14:43:22         13 hw-aa-1
2023-07-04 14:43:29         13 hw-aa-10
2023-07-04 14:43:59         13 hw-aa-100
2023-07-04 14:48:29         13 hw-aa-1000
2023-07-04 14:48:30         13 hw-aa-1001
2023-07-04 14:48:30         13 hw-aa-1002
2023-07-04 14:48:30         13 hw-aa-1003
An error occurred (BadDigest) when calling the ListObjectsV2 operation (reached max …
```

fixed marker being saved under wrong key in marker cache

---

pom.xml

This allows the project to work with maven 3.9+, as the modernizer no longer implicitly depends on plexus-utils.

update modernizer plugin to 2.6.0

---

README.md
src/main/java/org/gaul/s3proxy/Main.java
src/main/java/org/gaul/s3proxy/RegexBlobStore.java
src/main/java/org/gaul/s3proxy/S3ProxyConstants.java
src/test/java/org/gaul/s3proxy/RegexBlobStoreTest.java

This is probably a crazy idea, but I needed s3proxy to be able to rename the names of the blobs before they were written, so I have developed this middleware, and I am sharing it in case it might be useful to someone else.
In our case, we have a product that can only talk to S3, uploading blobs in a very limited way, with almost no configuration. Originally, blobs were uploaded to /prefix/&lt;source>/&lt;YYYYYY&gt;/&lt;MM&gt;/&lt;DD&gt; (e.g. /prefix/typea/2023/01/31). But due to other integrations that are not relevant, we needed the blobs to be uploaded in a path with the following format:
/prefix/date=&lt;YYYY&gt;-&lt;MM&gt;-&lt;DD&gt;/type=&lt;source&gt;
The regex is configured as:
s3proxy.regex-blobstore.match.&lt;regex name&gt; = &lt;regex match expression&gt; …

Add regex blob rename middleware

---

Dockerfile

The openjdk images are deprecated, and have critical vulnerabilities

change base image to eclipse-temurin

---

pom.xml

Bump jetty from 11.0.16 to 11.0.17. Jetty [11.0.17](https://github.com/jetty/jetty.project/releases/tag/jetty-11.0.17) fixes [CVE-2023-44487](https://github.com/advisories/GHSA-qppj-fm5r-hxr3), the HTTP2 reset vulnerability.

Bump jetty from 11.0.16 to 11.0.17

---

README.md
src/main/java/org/gaul/s3proxy/CrossOriginResourceSharing.java
src/main/java/org/gaul/s3proxy/S3ProxyHandler.java
src/test/java/org/gaul/s3proxy/CrossOriginResourceSharingAllowAllResponseTest.java
src/test/java/org/gaul/s3proxy/CrossOriginResourceSharingRuleTest.java

1. I found that DELETE method is not supported for CORS, which should be included. Refer to: [aws CORS config](https://docs.aws.amazon.com/AmazonS3/latest/userguide/ManageCorsUsing.html#cors-allowed-methods)
2. Currently, not all handle methods include "addCorsResponseHeader". I add it in all handle methods, because in most cases, the browser needs it.

Add DELETE and HEAD methods for CORS and CORS headers for all responses

---

src/main/java/org/gaul/s3proxy/S3Proxy.java

This improves the usability of the docker image, as it defaults to empty strings for both properties. With this fix, the docker image will work when only one of the endpoints are set.

treat null and empty string equally for endpoint properties

---

.github/workflows/ci-main.yml

Hi @gaul.
I took me a lot of time, reading and trial and error but I've finally come up with something to fix #479 and prepare for issue #591 I created myself yesterday.
I never used Github Actions myself so I googled a bit and found out that the [official action](https://docs.docker.com/build/ci/github-actions/push-multi-registries/) that is used to push to ghcr.io can also be used to push to docker.io without relying on regctl.
To do this one needs to pass [multiple image names](https://docs.docker.com/build/ci/github-actions/manage-tags-labels/) that are the base for building the targets to push to.
According to how the tags in the meta action are currently setup these changes resulted in 3 tags getting pushed to both ghcr.io and docker.io each time I pushed to my branch. (docker.io …

fix pushing images to docker.io

---

.github/workflows/ci-main.yml

Hi @gaul.
As promised I had another look and I missed the pipe character in the images-definition which leads to ignored newlines which then produce the wrong outputs in the meta step.
(I tested locally in a private repo and copied my changes to the fork afterwards, i must have missed this one)
Wrong version from the failed [action log](https://github.com/gaul/s3proxy/actions/runs/7485958402/job/20375361868#step:3:29) including "name" from line 35 before `,enable=true`:
```
Processing images input
name=ghcr.io/gaul/s3proxy/container name,enable=true
```
How it should look
```
Processing images input
name=ghcr.io/gaul/s3proxy/container,enable=true
```
The automatic build triggered through this PR looks [correct this time](https://github.com/gaul/s3proxy/actions/runs/7491610177/job/203932121 …

add missing pipe-character for images in meta step

---

.github/workflows/ci-main.yml

When by #595 pushing images to dockerhub is working again, this fixes #591 and creates an additional docker image for architecture linux/arm/v7.

create docker images for armv7

---

src/main/java/org/gaul/s3proxy/S3Proxy.java
src/main/resources/run-docker-container.sh

Adding the ability to configure s3proxy.maximum-timeskew using an environment variable.

Configure maximum-timeskew with environment variable

---

src/main/java/org/gaul/s3proxy/CaseInsensitiveImmutableMultimap.java
src/main/java/org/gaul/s3proxy/S3ProxyHandler.java

OpenStack Swift uses lower-case headers.  Fixes #664.

Look up HTTP headers while ignoring case

---

README.md
src/main/java/org/gaul/s3proxy/Main.java
src/main/java/org/gaul/s3proxy/S3ProxyConstants.java
src/main/java/org/gaul/s3proxy/StorageClassBlobStore.java
src/test/java/org/gaul/s3proxy/TierBlobStoreTest.java

This is best-effort and some storage classes do not map exactly, particularly for non-S3 object stores.  Fixes #625.

Add middleware to override storage class.

---

src/main/java/org/gaul/s3proxy/CrossOriginResourceSharing.java
src/main/java/org/gaul/s3proxy/S3Proxy.java
src/main/java/org/gaul/s3proxy/S3ProxyConstants.java
src/main/java/org/gaul/s3proxy/S3ProxyHandler.java
src/main/resources/run-docker-container.sh
src/test/java/org/gaul/s3proxy/CrossOriginResourceSharingAllowAllResponseTest.java
src/test/java/org/gaul/s3proxy/CrossOriginResourceSharingResponseTest.java
src/test/java/org/gaul/s3proxy/CrossOriginResourceSharingRuleTest.java
src/test/resources/s3proxy-cors.conf

Copy/paste of #668 description:
> I mentioned this in issue https://github.com/gaul/s3proxy/issues/667 but suffice to say that, while ETag is available as a header from many of the APIs in S3Proxy, the browser cannot access it since it's missing from the Access-Control-Expose-Headers list. To allow accessing this header from the browser, it needs to be added to the [Access-Control-Expose-Headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers) header.
This PR introduces a new config variable; `s3proxy.cors-exposed-headers` (or `S3PROXY_CORS_EXPOSED_HEADERS`) that allows configuring the values returned with `Access-Control-Expose-Headers` for CORS.

Adds feature allowing Access-Control-Expose-Headers configuration

---

src/main/java/org/gaul/s3proxy/S3ProxyHandler.java

Remove timestamp validation for requests that use query string authentication

---

README.md

Findify s3mock is archived.
Adobe s3mock is an active project.

README:  Adobe s3mock

---

src/main/java/org/gaul/s3proxy/AwsHttpHeaders.java
src/main/java/org/gaul/s3proxy/S3ProxyHandler.java

The Rust S3 SDK `aws-sdk-s3` (https://github.com/awslabs/aws-sdk-rust) sends the `x-amz-user-agent` header, but `s3proxy` does not know about it. This causes s3proxy to reject all requests from `aws-sdk-s3`.
This patch adds `x-amz-user-agent` to the `SUPPORTED_X_AMZ_HEADERS` list.

Allow x-amz-user-agent header

---

README.md
pom.xml
src/main/java/org/gaul/s3proxy/S3ErrorCode.java
src/main/java/org/gaul/s3proxy/S3ProxyHandlerJetty.java
src/main/java/org/gaul/s3proxy/azureblob/AzureBlobApiMetadata.java
src/main/java/org/gaul/s3proxy/azureblob/AzureBlobProviderMetadata.java
src/main/java/org/gaul/s3proxy/azureblob/AzureBlobStore.java
src/main/java/org/gaul/s3proxy/azureblob/AzureBlobStoreContextModule.java

This may replace the jclouds azureblob provider.  The implementation lacks some error codes and options.  Fixes #606.

Add azureblob-sdk provider backed by Azure SDK

---

src/main/resources/run-docker-container.sh

This update allows the `s3proxy.service-path` configuration introduced in https://github.com/gaul/s3proxy/pull/194 to be set when running S3Proxy via Docker

Allow setting service-path config when running via Docker

---

src/main/java/org/gaul/s3proxy/crypto/Decryption.java
src/test/java/org/gaul/s3proxy/EncryptedBlobStoreLiveTest.java

This resolves https://github.com/gaul/s3proxy/issues/698.
Open ended ranged requests to encrypted files resulted in incorrect Content-Length headers in the response because of a bug in the Decryption class.
In EncryptedBloBStore the length is set to `-1` by default. On open-ended ranged GET requests this value is passed to the `Decryption` constructor, which in turn only sets `outputLength` if an `offset` is given without a `length`, but `-1` is used to represent no length given. After this change the `outputLength` is set correctly in this constructor.
https://github.com/gaul/s3proxy/blob/master/src/main/java/org/gaul/s3proxy/EncryptedBlobStore.java#L375
@gaul The tests pass (locally) but I have not spend enough time with this codebase to reason about whether this change will break …

Set outputLength correctly on open ended range requests to encryptedBlobStore

---

.github/workflows/ci-main.yml
src/test/java/org/gaul/s3proxy/AwsSdkTest.java

Run Maven tests against azureblob-sdk in CI

---

src/main/java/org/gaul/s3proxy/azureblob/AzureBlobStore.java

This PR closes #352, #536.
Current behaviour is unaffected. If backend provider is `azureblob-sdk`, and both `identity`, and `credentials` are empty strings, authentication fallbacks to [DefaultAzureCredential](https://learn.microsoft.com/en-us/java/api/com.azure.identity.defaultazurecredential?view=azure-java-stable) and tries to login with multiple approaches, including managed identities.

Allow to use Azure managed identities for azureblob-sdk backend

---

.github/workflows/ci-main.yml
README.md
pom.xml
src/main/java/org/gaul/s3proxy/Quirks.java
src/main/java/org/gaul/s3proxy/S3ProxyHandler.java
src/main/java/org/gaul/s3proxy/nio2blob/Nio2BlobApiMetadata.java
src/main/java/org/gaul/s3proxy/nio2blob/Nio2BlobProviderMetadata.java
src/main/java/org/gaul/s3proxy/nio2blob/Nio2BlobStore.java
src/main/java/org/gaul/s3proxy/nio2blob/Nio2BlobStoreContextModule.java
src/main/resources/checkstyle.xml
src/test/java/org/gaul/s3proxy/AwsSdkTest.java
src/test/resources/s3proxy-transient-nio2.conf

This will enable multiple backends, e.g., jimfs (in-memory), filesystem, and possibly stranger things like Hadoop.  Currently only configured to use jimfs.  Fixes #697.

Add NIO.2 BlobStore

---

pom.xml
src/main/java/org/gaul/s3proxy/S3ProxyHandler.java

This indirectly addresses a CVE in commons-io that does not affect S3Proxy.

Upgrade to commons-fileupload2

---

src/main/resources/run-docker-container.sh

- https://github.com/gaul/s3proxy/pull/594 changed the hardcoded default value of `v4MaxNonChunkedRequestSize` to 128 MB
- The 128 MB default only kicks in if the `s3proxy.v4-max-non-chunked-request-size` config is not set
- However, when using the Docker image (in k8s, for example), if you don't explicitly override the `S3PROXY_V4_MAX_NON_CHUNKED_REQ_SIZE` env variable, the `run-docker-container.sh` sets this env var [1] to a default of 33554432 bytes (~32 MB)
- This commit changes this defualt to 128 MB, to match the default value defined in the code itself
This change makes it such that an un-initiated user running s3Proxy via Docker / k8s does not run into an error of the form:
400 MaxMessageLengthExceeded Your request was too big
, when uploading a file between 32 - 128 MB.
[1] …

docker: Match s3proxy.v4-max-non-chunked-request-size default (128 MB)

---

Dockerfile

PID 1 is special in Linux kernels; do not start the `java` process as PID 1. Instead, use dumb-init [1] as the init system and start it at PID 1.
This is generally done for two main reasons [1]:
- Signal handling When k8s terminates a Pod, it sends a SIGTERM to PID 1 in the containers. When a non-PID-1 process receives SIGTERM and it does not register a SIGTERM handler, the kernel will fall back to the default behavior for a SIGTERM signal: killing the process.
However, this is not the case for PID 1; the kernel does not fallback to killing the PID 1 process if no SIGTERM handler is registered. This means that the SIGTERM will have no effect on the process. k8s will wait for `terminationGracePeriodSeconds` (default: 30 seconds) and only then SIGKILL the process (having wasted 30 seconds …

Docker: Use dumb-init as init system

---

src/main/java/org/gaul/s3proxy/S3ProxyHandler.java

This gives better errors.  Also use case-insensitive comparisons.

Check supported headers before signature

---

src/main/java/org/gaul/s3proxy/LatencyBlobStore.java
src/main/java/org/gaul/s3proxy/Main.java
src/main/java/org/gaul/s3proxy/S3ProxyConstants.java
src/main/java/org/gaul/s3proxy/ThrottledInputStream.java
src/test/java/org/gaul/s3proxy/LatencyBlobStoreTest.java

Allows running performance tests with s3proxy using simulated latency and read/write speed
- Added LatencyBlobStore, ThrottledInputStream
- Parse properties from s3proxy.conf
```
s3proxy.latency-blobstore.*.latency=1000 # Add 1000ms latency to all operations
s3proxy.latency-blobstore.put.latency=2000 # Override put blob to 2000ms latency
s3proxy.latency-blobstore.put.speed=10 # Limit put blob to 10 kb/s
```

Add latency blobstore middleware

---

README.md
src/main/java/org/gaul/s3proxy/Main.java
src/main/java/org/gaul/s3proxy/NoCacheBlobStore.java
src/main/java/org/gaul/s3proxy/S3ProxyConstants.java
src/main/resources/run-docker-container.sh
src/test/java/org/gaul/s3proxy/NoCacheBlobStoreTest.java

A workaround for issue https://github.com/gaul/s3proxy/issues/848 where jclouds is not capable of properly handling HTTP 304 responses.
Adds an optional middleware `NoCacheBlobStore` that for GET requests cleans the `GetOptions` from the following conditional headers:
- If-None-Match
- If-Match
- If-Modified-Since
- If-Unmodified-Since
Instead of returning a HTTP 304 in theses cases, always the full object is returned.

Add NoCacheBlobStore

---

src/main/java/org/gaul/s3proxy/EncryptedBlobStore.java
src/main/java/org/gaul/s3proxy/crypto/Encryption.java
src/test/java/org/gaul/s3proxy/EncryptedBlobStoreTest.java

Fix for https://github.com/gaul/s3proxy/issues/848
The exceptions caught in `EncryptedBlobStore` were too broad, so that the jclouds `HttpResponseException` was not proxied to the client e.g. in a HTTP 304 conditional request response case.
Refactored the catch blocks to catch only the more specific exceptions related to the actual encryption.
The general `S3ProxyHandlerJetty` handler then handles the others:
https://github.com/gaul/s3proxy/blob/master/src/main/java/org/gaul/s3proxy/S3ProxyHandlerJetty.java#L88

Fix EncryptedBlobStore error handling
